name: Generate Snake2

on:
  schedule:
    - cron: "0 0 * * *"  # her gün çalışır
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: RavanGuliyeff
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          svg_settings: |
            {
              "palette": "github-dark",
              "animation_duration": 3000,
              "width": 1080,
              "height": 400
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit snake
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake-dark.svg output/github-contribution-grid-snake.svg
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output/github-contribution-grid-snake.svg
          git commit -m "update snake" || echo "no changes"
          git push
