name: Generate snake game v2
on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: RavanGuliyeff
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=orange&color_dots=#575757,#74cc8f,#44a662,#228240,#065e21
            dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/retro-snake.svg?palette=github-dark&color_snake=#00FF00&color_dots=#000000,#006400,#008000,#00FF00,#00CED1
            dist/fire-snake.svg?palette=github-dark&color_snake=#FF4500&color_dots=#8B0000,#FF4500,#FF8C00,#FFA500,#FFD700
            dist/neon-snake.svg?palette=github-dark&color_snake=#9400D3&color_dots=#4B0082,#6A5ACD,#9400D3,#BA55D3,#DA70D6
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
