name: Generate snake game v2
on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: RavanGuliyeff
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=orange&color_dots=#575757,#74cc8f,#44a662,#228240,#065e21
            dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
